### ISSUE TITLE
Add deployment pipeline jobs

### ISSUE THREAD

**Issue by pli888** [gigascience/gigadb-website#1066]
* [x] Create certificates for Docker instances for staging and live bastion servers by copying relevant Ansible roles
* [x] Temporarily comment out irrelevant jobs in pipeline to save time
* Add new jobs into .gitlab-config file which is included in the gitlab-ci.yml:
  * [x] GigaReviewTest
  * [x] GigaReviewBuildStaging
  * [x] GigaReviewDeployStaging
  * [ ] GigaReviewBuildLive
  * [ ] GigaReviewDeployLive
* [x] Remove GigaReview deployment code block in the Bastion playbook
* [ ] Ensure the jobs above use Gitlab's DAG job dependency mechanism (use keyword ``needs: ["(previous job)"]``) to stay independent from other apps pipeline - done by PR #1085
* [ ] Fix (configuration) issue where GigaReview test job is erroring in Upstream pipeline for the ``develop`` branch

**Comment by rija** [comment]
For reference here is the snippet (that uses wrong approach) from bastion playbook currently used to deploy and setup gigareview: 
```
- name: Unarchive a file that needs to be downloaded (added in 2.0)
    ansible.builtin.unarchive:
      src: https://github.com/rija/gigadb-website/archive/refs/heads/review-workers.zip
      dest: /home/centos
      remote_src: yes
      owner: centos
      group: centos

  - name: Install local gigareview .env
    ansible.builtin.copy:
      src: ../../../../gigareview/.env
      dest: /home/centos/gigadb-website-review-workers/gigareview
      owner: centos
      group: centos

  - name: Replace environment to staging
    ansible.builtin.replace:
      path: /home/centos/gigadb-website-review-workers/gigareview/.env
      regexp: 'REVIEW_ENV=\w+'
      replace: 'REVIEW_ENV={{ gigadb_environment }}'

  - name: Start gigareview on bastion host
    ansible.builtin.command: ./up.sh
    args:
      chdir: /home/centos/gigadb-website-review-workers/gigareview

  - name: Setup cronjob to automate Editorial Manager report ingest
    ansible.builtin.cron:
      name: "Fetch latest EM reports"
      minute: "00"
      hour: "13"
      user: "centos"
      job: "cd /home/centos/gigadb-website-review-workers/gigareview ; /usr/local/bin/docker-compose run --rm console ./yii fetch-reports/fetch latest 2> $HOME/logs/em_reports_ingest_errors.log 1> $HOME/logs/em_reports_ingest_output.log"
```

Puttting it here,as I need to remove that snippet from my current PR to save on resources
