### ISSUE TITLE
Consider less specific CSS selector for global styles

### ISSUE THREAD

**Issue by luistoptal** [gigascience/gigadb-website#1388]
## Description

In file `less/current/base/scaffolding.less` the following styles can be found:

```css
* {
  font-size: @font-size-base;
  font-family: @font-family-base;
  line-height: @line-height-base;
}
```

This selector is highly specific and applies those styles to every single element. This means that styles that change those properties need to be equally specific and cannot rely of cascading of styles from parent to children.

Consider whether an alternative approach can work without requiring intensive refactoring:

```css
body {
  font-size: @font-size-base;
  font-family: @font-family-base;
  line-height: @line-height-base;
}
```

## Acceptance criteria

- [ ] Try using a less specific selector and do the replacement if it's trivial
