### ISSUE TITLE
[S740] Configure containers to rotate their logs

### ISSUE THREAD

**Issue by rija** [gigascience/gigadb-website#787]
update container service defintion to enable log rotation.

Reference: 
https://docs.docker.com/compose/compose-file/compose-file-v3/#logging

Every container needs the same setting, so avoid duplication, use YAML anchors

https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/

We need to do that for development compose file (``docker-compose.yml``)  and for production compose file (``docker-compose.production-envs.yml``) because we may need different value of max size in each case.

Additional resources:
* https://nickjanetakis.com/blog/docker-tip-82-using-yaml-anchors-and-x-properties-in-docker-compose
* and from this blog: https://yuriktech.com/2020/03/21/Collecting-Docker-Logs-With-Loki/
there is this example: 
```
# logger driver - change this driver to ship all container logs to a different location
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
services:
  my_service:
    *logging
    container_name: xxx
    image: xxx/xxx
  another_cool_service:
    *logging
    container_name: xxxx
    image: xxxx/xxxx
```
